/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.BubbleSort;
import Clases.MergeSort;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaime Sierra
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        tabla();
    }
    long startTimeBS, endTimeBS, timeBS, startTimeMS, endTimeMS, timeMS;
    File infor = new File("src/Archivos/info");

    void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Número de claves");
        modelo.addColumn("Tamaño de las claves");
        modelo.addColumn("Promedio de Instrucciones BS");
        modelo.addColumn("Promedio de Instrucciones MS");
        modelo.addColumn("Promedio de Tiempo BS");
        modelo.addColumn("Promedio de Tiempo MS");
        jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Digite el número de claves a generar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 24));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        jLabel2.setText("Digite el tamaño de las claves:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, -1));

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 90, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 70, 30));

        jLabel3.setText("Valor inicial:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, 30));

        jLabel4.setText("Valor final:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 60, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 70, 30));

        jLabel5.setText("Incremento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 60, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 70, 30));

        jButton2.setText("GENERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número de claves", "Tamaño de las claves", "Promedio de Instrucciones BS", "Promedio de Instrucciones MS", "Promedio de Tiempo BS", "Promedio de Tiempo MS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 920, 370));

        jLabel6.setText("Generar a un rango específico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    public static BigInteger randomBig(int digitosDecimales) {
        Random numeroRandom = new Random();
        BigInteger bi = BigInteger.ZERO;
        for (int i = 0; i < digitosDecimales; i++) {
            int ir = i == 0 ? numeroRandom.nextInt(9) + 1 : numeroRandom.nextInt(10);
            bi = bi.multiply(BigInteger.TEN).add(BigInteger.valueOf(ir));
        }

        return bi;

    }

    public void mostrar() {

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int numberKeys = Integer.parseInt(jTextField1.getText());
            int keysSize = Integer.parseInt(jTextField2.getText());
            BubbleSort bu = new BubbleSort();
            MergeSort me = new MergeSort();

            BigInteger vec2[] = new BigInteger[numberKeys];
            BigInteger vec3[] = new BigInteger[vec2.length];

            for (int i = 0; i < vec2.length; i++) {
                vec2[i] = vec3[i] = randomBig(keysSize);

            }
            startTimeBS = System.currentTimeMillis();
            bu.recursiveBubble(vec3);
            endTimeBS = System.currentTimeMillis();
            timeBS = endTimeBS - startTimeBS;

            startTimeMS = System.currentTimeMillis();
            me.sort(vec2, 0, vec2.length - 1);
            endTimeMS = System.currentTimeMillis();
            timeMS = endTimeBS - startTimeBS;

            //Modelo
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Número de claves");
            modelo.addColumn("Tamaño de las claves");
            modelo.addColumn("Promedio de Instrucciones BS");
            modelo.addColumn("Promedio de Instrucciones MS");
            modelo.addColumn("Promedio de Tiempo BS");
            modelo.addColumn("Promedio de Tiempo MS");

            String[] a = {String.valueOf(numberKeys), String.valueOf(keysSize), String.valueOf(bu.getContadorInstrucciones()), String.valueOf(me.getContadorInstrucciones()), String.valueOf(timeBS), String.valueOf(timeMS)};
            modelo.addRow(a);
            jTable1.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar número enteros");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

     public static void guardarArchivo(File archivo, String[] vec) throws IOException {
        BufferedWriter bw;

        bw = new BufferedWriter(new FileWriter(archivo));
        
        for (int i = 0; i < vec.length; i++) {
            if (archivo.exists()) {
                bw.write(vec[i]);
                bw.newLine();
            } else {
                bw.write(String.valueOf(vec[i]));
                bw.newLine();
            }
        }
        bw.close();

    }
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int keysSize = Integer.parseInt(jTextField2.getText());
        BubbleSort bu = new BubbleSort();
        MergeSort me = new MergeSort();
        String [] info = new String[6];
        
        //Modelo
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Número de claves");
        modelo.addColumn("Tamaño de las claves");
        modelo.addColumn("Promedio de Instrucciones BS");
        modelo.addColumn("Promedio de Instrucciones MS");
        modelo.addColumn("Promedio de Tiempo BS");
        modelo.addColumn("Promedio de Tiempo MS");

        BigInteger vec2[] = new BigInteger[Integer.parseInt(jTextField4.getText())];
        BigInteger vec3[] = new BigInteger[vec2.length];

        for (int i = 0; i < vec2.length; i += Integer.parseInt(jTextField5.getText())) {
            vec2[i] = vec3[i] = randomBig(keysSize);
            System.out.println("Se generaron : "+i);
            startTimeBS = System.currentTimeMillis();
            bu.recursiveBubble(vec3);
            endTimeBS = System.currentTimeMillis();
            timeBS = endTimeBS - startTimeBS;

            startTimeMS = System.currentTimeMillis();
            me.sort(vec2, 0, vec2.length - 1);
            endTimeMS = System.currentTimeMillis();
            timeMS = endTimeBS - startTimeBS;
            System.out.println("Se organizaron");

        }

        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
