/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.BubbleSort;
import Clases.MergeSort;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Panel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.math.BigInteger;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jaime Sierra
 */
public class Vistas extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Vistas() {
        initComponents();
        tabla();
    }
    long startTimeBS, endTimeBS, timeBS, startTimeMS, endTimeMS, timeMS;
    File infor = new File("src/Archivos/info.txt");
    File BubbleSort = new File("src/Archivos/Bubble_Sort.csv");
   

    void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Número de claves");
        modelo.addColumn("Tamaño de las claves");
        modelo.addColumn("Promedio de Instrucciones BS");
        modelo.addColumn("Promedio de Instrucciones MS");
        modelo.addColumn("Promedio de Tiempo BS");
        modelo.addColumn("Promedio de Tiempo MS");
        jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1050, 180));

        jLabel1.setText("Digite el número máximo de claves a generar:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 24));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        jLabel2.setText("Digite el tamaño de las claves:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, -1));

        jButton2.setText("GENERAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número de claves", "Tamaño de las claves", "Promedio de Instrucciones BS", "Promedio de Instrucciones MS", "Promedio de Tiempo BS", "Promedio de Tiempo MS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1260, 360));

        jButton3.setText("GENERAR ARCHIVO EXCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 210, 30));

        jButton4.setText("MOSTRAR ARCHIVOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 190, 30));

        jLabel3.setText("Digite el incremento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    public static BigInteger randomBig(int digitosDecimales) {
        Random numeroRandom = new Random();
        BigInteger bi = BigInteger.ZERO;
        for (int i = 0; i < digitosDecimales; i++) {
            int ir = i == 0 ? numeroRandom.nextInt(9) + 1 : numeroRandom.nextInt(10);
            bi = bi.multiply(BigInteger.TEN).add(BigInteger.valueOf(ir));
        }

        return bi;

    }

    public void mostrar() {

    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int numberMaxKeys = Integer.parseInt(jTextField1.getText());
            int keysSize = Integer.parseInt(jTextField2.getText()), cont = 0;
            BubbleSort bu = new BubbleSort();
            MergeSort me = new MergeSort();
            //Modelo
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Conjunto de datos");
            modelo.addColumn("Número de claves");
            modelo.addColumn("Tamaño de las claves");
            modelo.addColumn("Promedio de Instrucciones BS");
            modelo.addColumn("Promedio de Instrucciones MS");
            modelo.addColumn("Promedio de Tiempo BS");
            modelo.addColumn("Promedio de Tiempo MS");

            for (int w = 100; w < numberMaxKeys; w += Integer.parseInt(jTextField3.getText())) {
                cont++;
                BigInteger vec2[] = new BigInteger[w];
                BigInteger vec3[] = new BigInteger[vec2.length];

                for (int i = 0; i < vec2.length; i++) {
                    vec2[i] = vec3[i] = randomBig(keysSize);

                }
                startTimeBS = System.nanoTime();
                bu.recursiveBubble(vec3);
                endTimeBS = System.nanoTime();
                timeBS = endTimeBS - startTimeBS;

                startTimeMS = System.nanoTime();
                me.sort(vec2, 0, vec2.length - 1);
                endTimeMS = System.nanoTime();
                timeMS = endTimeBS - startTimeBS;

                String[] a = new String[7];
                a[0] = String.valueOf(cont);
                a[1] = String.valueOf(w);
                a[2] = String.valueOf(keysSize);
                a[3] = String.valueOf(bu.getContadorInstrucciones());
                a[4] = String.valueOf(me.getContadorInstrucciones());
                a[5] = String.valueOf(timeBS);
                a[6] = String.valueOf(timeMS);

                System.out.println("Se generaron " + w + " claves");
                System.out.println("Tamaño: " + keysSize + " Número promedio de Instrucciones BS: " + bu.getContadorInstrucciones());
                System.out.println("Número promedio de Instrucciones MS: " + me.getContadorInstrucciones());
                System.out.println("Tiempos promedio BS y MS respectivamente: " + timeBS + " " + timeMS);
                System.out.println("\n");
                modelo.addRow(a);
                guardarArchivo(BubbleSort, a, "PARA n= " + String.valueOf(w));
                jTable1.setModel(modelo);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar número enteros");
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    public void abrirarchivo(String archivo) {

        try {

            File objetofile = new File(archivo);
            Desktop.getDesktop().open(objetofile);

        } catch (IOException ex) {

            System.out.println(ex);
        }
    }

    


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        abrirarchivo("src/Archivos/Bubble_Sort.csv");

        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     *
     * @param archivo Archivo a crear
     * @param vec Vector que contiene la información que será guardada en el
     * archivo.
     * @param text Texto de referencia del archivo.
     * @throws IOException Exception.
     */
    public static void guardarArchivo(File archivo, String[] vec, String text) throws IOException {
        BufferedWriter bw;

        bw = new BufferedWriter(new FileWriter(archivo));
        if (archivo.exists()) {
            bw.write(text);
            bw.newLine();

        }
        for (int i = 0; i < vec.length; i++) {
            if (archivo.exists()) {
                bw.write(vec[i]);
                bw.newLine();
            } else {
                bw.write(vec[i]);
                bw.newLine();
            }
        }
        bw.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
